In [18]:
import numpy as np
import pandas as pd

In [19]:
df = pd.read_csv('50sensor_power_2tx_latlon_5g.csv')
df.head()

time   tx  id         power      lon       lat    dbm
0  0.00  500  16  4.996616e-13  3.06045  50.63294 -123.0
1  0.02  500  16  5.004682e-13  3.06045  50.63294 -123.0
2  0.04  500  16  5.013803e-13  3.06045  50.63294 -123.0
3  0.06  500  16  5.021966e-13  3.06045  50.63294 -123.0
4  0.08  500  16  5.031786e-13  3.06045  50.63294 -123.0

In [21]:
df['dbm'].min()

-210.0

In [22]:
df['dbm'].max()

-40.0

In [ ]:
-160

In [23]:
a = df[df['time']==0.0]
a.head()

time   tx  id         power      lon       lat    dbm
0       0.0  500  16  4.996616e-13  3.06045  50.63294 -123.0
423     0.0  501  20  1.667439e-10  3.06742  50.63554  -98.0
3953    0.0  501  26  6.945485e-11  3.06920  50.63502 -102.0
6954    0.0  501  10  2.750240e-12  3.06965  50.63221 -116.0
12697   0.0  500  27  3.472780e-11  3.06757  50.63208 -105.0

In [29]:
a[['time','id','dbm']].T

0       423     3953    6954    12697   15682   18683   20971   23972   \
time     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
id      16.0    20.0    26.0    10.0    27.0    14.0    25.0    41.0    19.0   
dbm   -123.0   -98.0  -102.0  -116.0  -105.0   -85.0  -118.0  -115.0  -112.0   

      26973   ...  73801   75917   80326   83327   87891   90702   96337   \
time     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
id      40.0  ...    22.0    28.0    23.0    48.0    37.0    21.0     7.0   
dbm   -113.0  ...  -112.0   -55.0   -93.0  -102.0  -110.0   -97.0   -97.0   

      98175   101174  104158  
time     0.0     0.0     0.0  
id      34.0    44.0    31.0  
dbm    -73.0   -60.0  -110.0  

[3 rows x 37 columns]

In [25]:
b=df['id'].value_counts().reset_index()
b

index    id
0      33  3001
1      19  3001
2      20  3001
3      15  3001
4      36  3001
5      32  3001
6      18  3001
7      17  3001
8       2  3001
9      38  3001
10     47  3001
11     41  3001
12     42  3001
13     14  3001
14     28  3001
15     23  3001
16     26  3001
17     29  3000
18     34  2999
19     48  2998
20     45  2997
21     27  2985
22     44  2984
23     49  2930
24     10  2902
25     31  2893
26     37  2811
27      9  2729
28     40  2570
29     21  2308
30     25  2288
31     22  2116
32     35  1874
33      7  1838
34     13  1566
35     43  1524
36      5  1503
37      6  1408
38     30  1338
39      8  1080
40      4   598
41     11   529
42     39   459
43     16   423
44     12   382
45     50     2

In [26]:
b['index'].max()

50

In [27]:
b['index'].min()

2

In [147]:
a = [
    [[1,1],[1,1]],[[2,2],[2,2]],[[3,3],[3,3]],[[4,4],[4,4]],[[5,5],[5,5]]
]
a

[[[1, 1], [1, 1]],
 [[2, 2], [2, 2]],
 [[3, 3], [3, 3]],
 [[4, 4], [4, 4]],
 [[5, 5], [5, 5]]]

In [36]:
b=np.array(a)
b

array([[[1, 1],
        [1, 1]],

       [[2, 2],
        [2, 2]],

       [[3, 3],
        [3, 3]],

       [[4, 4],
        [4, 4]],

       [[5, 5],
        [5, 5]]])

In [ ]:
1 2 3
2 3 4
3 4 5

In [37]:
b.shape

(5, 2, 2)

In [38]:
time_step = 2

In [44]:
data_x = []
data_y = []
for i in range(b.shape[0]-time_step):
    print(i)
    data_x.append(b[i : i+time_step])
    data_y.append(b[i+time_step])

0
1
2


In [49]:
np.array(data_x)

array([[[[1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2]]],


       [[[2, 2],
         [2, 2]],

        [[3, 3],
         [3, 3]]],


       [[[3, 3],
         [3, 3]],

        [[4, 4],
         [4, 4]]]])

In [54]:
np.array(data_x).shape

(3, 2, 2, 2)

In [50]:
data_y

[array([[3, 3],
        [3, 3]]),
 array([[4, 4],
        [4, 4]]),
 array([[5, 5],
        [5, 5]])]

In [67]:
np.array(data_y).shape

(3, 2, 2)

In [60]:
# reshape input to be [samples, time steps, features]
np.reshape(np.array(data_x), (np.array(data_x).shape[0], 1, 8))

array([[[1, 1, 1, 1, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 4, 4, 4, 4]]])

In [69]:
np.reshape(np.array(data_y),(np.array(data_y).shape[0], 1,4))

array([[[3, 3, 3, 3]],

       [[4, 4, 4, 4]],

       [[5, 5, 5, 5]]])

In [100]:
# LSTM for international airline passengers problem with regression framing
import numpy as np
import matplotlib.pyplot as plt
from pandas import read_csv
import math
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error

In [106]:
# create and fit the LSTM network
model = Sequential()
model.add(LSTM(20, input_shape=(1, time_step*4)))
# model.add(LSTM(4))
model.add(Dense(4))
model.compile(loss='mean_squared_error', optimizer='adam')
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_15 (LSTM)              (None, 20)                2320      
                                                                 
 dense_5 (Dense)             (None, 4)                 84        
                                                                 
Total params: 2,404
Trainable params: 2,404
Non-trainable params: 0
_________________________________________________________________


In [107]:
model.fit(np.reshape(np.array(data_x), (np.array(data_x).shape[0], 1, 8)), np.reshape(np.array(data_y),(np.array(data_y).shape[0], 1,4)), epochs=100, batch_size=1, verbose=2)

Epoch 1/100
3/3 - 1s - loss: 16.6845 - 1s/epoch - 411ms/step
Epoch 2/100
3/3 - 0s - loss: 16.3888 - 5ms/epoch - 2ms/step
Epoch 3/100
3/3 - 0s - loss: 16.1007 - 4ms/epoch - 1ms/step
Epoch 4/100
3/3 - 0s - loss: 15.7956 - 4ms/epoch - 1ms/step
Epoch 5/100
3/3 - 0s - loss: 15.5309 - 5ms/epoch - 2ms/step
Epoch 6/100
3/3 - 0s - loss: 15.2629 - 6ms/epoch - 2ms/step
Epoch 7/100
3/3 - 0s - loss: 15.0116 - 8ms/epoch - 3ms/step
Epoch 8/100
3/3 - 0s - loss: 14.6941 - 6ms/epoch - 2ms/step
Epoch 9/100
3/3 - 0s - loss: 14.4465 - 9ms/epoch - 3ms/step
Epoch 10/100
3/3 - 0s - loss: 14.1488 - 5ms/epoch - 2ms/step
Epoch 11/100
3/3 - 0s - loss: 13.8615 - 10ms/epoch - 3ms/step
Epoch 12/100
3/3 - 0s - loss: 13.5136 - 8ms/epoch - 3ms/step
Epoch 13/100
3/3 - 0s - loss: 13.2318 - 7ms/epoch - 2ms/step
Epoch 14/100
3/3 - 0s - loss: 12.9106 - 10ms/epoch - 3ms/step
Epoch 15/100
3/3 - 0s - loss: 12.5620 - 6ms/epoch - 2ms/step
Epoch 16/100
3/3 - 0s - loss: 12.2386 - 8ms/epoch - 3ms/step
Epoch 17/100
3/3 - 0s - loss: 

In [118]:
model.predict(np.reshape(np.array([c_x]), (np.array([c_x]).shape[0], 1, 8)))

array([[4.2382035, 4.5002723, 4.383644 , 4.3145447]], dtype=float32)

In [114]:
c_x = [
    [[4,4],[4,4]],[[5,5],[5,5]]
]
c_x

[[[4, 4], [4, 4]], [[5, 5], [5, 5]]]

In [115]:
np.array([c_x]).shape

(1, 2, 2, 2)

In [116]:
c_y=[[6,6],[6,6]]
c_y

[[6, 6], [6, 6]]

In [117]:
np.array([c_y]).shape

(1, 2, 2)

In [86]:
np.reshape(np.array([c_x]), (np.array([c_x]).shape[0], 1, 8))

array([[[4, 4, 4, 4, 5, 5, 5, 5]]])

In [88]:
np.reshape(np.array([c_y]),(np.array([c_y]).shape[0], 1,4))

array([[[6, 6, 6, 6]]])

In [180]:
a = pd.DataFrame([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
    [4,4,4,4],
    [5,5,5,5],
    [6,6,6,6],
#     [7,7,7,7]
],columns=['fea1','fea2','fea3','fea4'])
a

fea1  fea2  fea3  fea4
0     1     1     1     1
1     2     2     2     2
2     3     3     3     3
3     4     4     4     4
4     5     5     5     5
5     6     6     6     6

In [181]:
a.shape

(6, 4)

In [182]:
time_step = 2
b = a.shift(-time_step,axis=0).dropna(axis=0)
b

fea1  fea2  fea3  fea4
0   3.0   3.0   3.0   3.0
1   4.0   4.0   4.0   4.0
2   5.0   5.0   5.0   5.0
3   6.0   6.0   6.0   6.0

In [201]:
new_a = a.loc[:4,:].to_numpy()
new_a

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5]], dtype=int64)

In [202]:
new_a.shape

(5, 4)

In [204]:
new_a=[
    [[1, 1, 1, 1],[2, 2, 2, 2]],
    [[2, 2, 2, 2],[3, 3, 3, 3]],
    [[3, 3, 3, 3],[4, 4, 4, 4]],
    [[4, 4, 4, 4],[5, 5, 5, 5]],
]

In [203]:
b.to_numpy()

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [207]:
np.array(new_a).shape

(4, 2, 4)

In [208]:
# create and fit the LSTM network
model = Sequential()
model.add(LSTM(20, input_shape=(2,4)))
# model.add(LSTM(4))
model.add(Dense(4))
model.compile(loss='mean_squared_error', optimizer='adam')
model.summary()

Model: "sequential_24"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_28 (LSTM)              (None, 20)                2000      
                                                                 
 dense_9 (Dense)             (None, 4)                 84        
                                                                 
Total params: 2,084
Trainable params: 2,084
Non-trainable params: 0
_________________________________________________________________


In [211]:
model.fit(np.array(new_a),b.to_numpy(),epochs=100, batch_size=1, verbose=2)

Epoch 1/100
4/4 - 1s - loss: 22.0820 - 1s/epoch - 298ms/step
Epoch 2/100
4/4 - 0s - loss: 21.5913 - 7ms/epoch - 2ms/step
Epoch 3/100
4/4 - 0s - loss: 20.9367 - 7ms/epoch - 2ms/step
Epoch 4/100
4/4 - 0s - loss: 20.3978 - 9ms/epoch - 2ms/step
Epoch 5/100
4/4 - 0s - loss: 19.7738 - 10ms/epoch - 2ms/step
Epoch 6/100
4/4 - 0s - loss: 19.1864 - 11ms/epoch - 3ms/step
Epoch 7/100
4/4 - 0s - loss: 18.6957 - 9ms/epoch - 2ms/step
Epoch 8/100
4/4 - 0s - loss: 18.0966 - 11ms/epoch - 3ms/step
Epoch 9/100
4/4 - 0s - loss: 17.5149 - 7ms/epoch - 2ms/step
Epoch 10/100
4/4 - 0s - loss: 16.8489 - 13ms/epoch - 3ms/step
Epoch 11/100
4/4 - 0s - loss: 16.2676 - 10ms/epoch - 3ms/step
Epoch 12/100
4/4 - 0s - loss: 15.6219 - 10ms/epoch - 3ms/step
Epoch 13/100
4/4 - 0s - loss: 15.0789 - 8ms/epoch - 2ms/step
Epoch 14/100
4/4 - 0s - loss: 14.3424 - 10ms/epoch - 2ms/step
Epoch 15/100
4/4 - 0s - loss: 13.7080 - 10ms/epoch - 2ms/step
Epoch 16/100
4/4 - 0s - loss: 12.9297 - 6ms/epoch - 1ms/step
Epoch 17/100
4/4 - 0s - 

In [215]:
np.array([[[4, 4, 4, 4],[5, 5, 5, 5]]]).shape

(1, 2, 4)

In [216]:
model.predict(np.array([[[4, 4, 4, 4],[5, 5, 5, 5]]]))

array([[4.9476333, 5.3589125, 5.2252784, 5.1576185]], dtype=float32)

In [192]:
a.loc[:4,:]

fea1  fea2  fea3  fea4
0     1     1     1     1
1     2     2     2     2
2     3     3     3     3
3     4     4     4     4
4     5     5     5     5

In [134]:
import random

In [146]:
random.choice(['德国','新加坡'])

'德国'

In [5]:
config = ConfigReader.GetModelConfig("./Temp/my_config.json")
config

{'grid_size': 100,
 'generator_lr': 0.001,
 'discriminator_lr': 0.001,
 'pre_train_epoch': 1,
 'train_epoch': 1,
 'batch_size': 20,
 'mean_shift_radius': 25,
 'mean_shift_bandwith': 20,
 'strange_num': 0,
 'low_data_path': 'Temp/low_data.npy',
 'high_data_path': 'Temp/high_data.npy',
 'model_out_path': 'Temp/SI-AGAN.pth',
 'log_path': 'Temp/SI-AGAN-log.txt'}

In [6]:
GENERATOR_LR = config["generator_lr"]  # 0.001
DISCRIMINATOR_LR = config["discriminator_lr"]  # 0.001
PRE_TRAIN_EPOCH = config["pre_train_epoch"]  # 2
TRAIN_EPOCH = config["train_epoch"]  # 10
BATCH_SIZE = config["batch_size"]  # 5
MODEL_OUT_PATH = config["model_out_path"]  # "../Temp/Generator.pth"
UP_SAMPLE = 1
IS_CUDA = False
log_path = config["log_path"]
low_data_path = config['low_data_path']
high_data_path = config['high_data_path']
model_out_path = config['model_out_path']

In [15]:
low_data = np.load(low_data_path)
low_data.shape

(2700, 100, 100)

In [16]:
for i in range(low_data[0].shape[0]):
    print(i, low_data[0][i])

0 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0 -97   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0]
1 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0 -80   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0  

In [ ]:
time_stemp = 5

In [30]:
high_data = np.load(high_data_path)
high_data.shape

(2700, 100, 100)

In [31]:
for i in range(high_data[0].shape[0]):
    print(i, high_data[0][i])

0 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan  nan  nan  nan  nan  nan  nan -97.  nan  nan  nan  nan  nan  nan
  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan  nan]
1 [         nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
 -97.55630418 -95.03187077 -93.72438421 -92.68295255 -91.60388488
 -90.48220251 -89.33374984 -88.17966792 -87.11514639 -86.16136804
 -85.31099527 -84.5566905  -83.89111614 -83.30693462 -82.79680834
 -82.35339973          na